### ISSUE TITLE
[BUG] Infraction warning uses spam warning config

### ISSUE THREAD

**Issue by pwnker** [4drian3d/ChatRegulator#12]
No matter what you set the infraction warning in messages.yml it will always use the warning set for spam.

**Comment by 4drian3d** [comment]
I am currently finishing the development of version 2 of the plugin, in this version those bugs will be fixed.

I am leaving this issue open until I release that version.

**Comment by 4drian3d** [comment]
I thought I had already solved it, but I found the bug. Thanks for reporting it
