### ISSUE TITLE
[BUG] The plugin does not work correctly

### ISSUE THREAD

**Issue by Widify-dev** [4drian3d/ChatRegulator#15]
**Describe the bug**
Nothing happens when there is a violation

**Expected behavior**
If you try to violate and look at the statistics, then it is added, but the violator is not punished, does not write anything. I used the usual settings, it didn't help either

**Additional context**
There are no errors. Config -- https://p.reflex.rip/eyab.bash.
 Velocity v3.1.1

**Comment by 4drian3d** [comment]
I probably just found the cause of the failure, but just in case you can specify which check or function is failing?

**Comment by Widify-dev** [comment]
> I probably just found the cause of the failure, but just in case you can specify which check or function is failing?

All functions not work :(

**Comment by 4drian3d** [comment]
https://github.com/4drian3d/ChatRegulator/releases/tag/2.1.0
