### ISSUE TITLE
Allow Cyrillic in Unicode

### ISSUE THREAD

**Issue by Widify-dev** [4drian3d/ChatRegulator#17]
The entire Russian alphabet is blocked in Unicode, perhaps this is correct, but many Russian players play minecraft.

Allow the Unicode module to use the entire Russian alphabet using pattern.

**Comment by 4drian3d** [comment]
I will add a configuration option to add allowed characters. Currently in v3 there is API to do this, but I will make it configurable.

**Comment by 4drian3d** [comment]
Fully implemented in cf160b0896fed37666f1a0fb7b6b19cc632f4870
