### ISSUE TITLE
[Bug] The flood module does not work correctly

### ISSUE THREAD

**Issue by Widify-dev** [4drian3d/ChatRegulator#18]
If you try to write more than a message, a warning pops up.

I propose to rewrite the system and check every word, not the whole sentence, because the most common sentence is blocked, although there is a large limitation in the config

**Comment by 4drian3d** [comment]
It should been fixed since https://github.com/4drian3d/ChatRegulator/commit/cdc2e8367df105ef8a228bff96a48bd9e6bdf4fc
