### ISSUE TITLE
[Feature Request] Adding a white list

### ISSUE THREAD

**Issue by Widify-dev** [4drian3d/ChatRegulator#19]
It doesn't matter if it was a command or a message, but it's a useful thing.

**Describe the solution you'd like**
In the configuration, add a new whitelist block, in which you can write any words that will be ignored by pattern (regex). For example, allow a link to the server's store, IP address, and so on

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by 4drian3d** [comment]
I don't see the need to add a whitelist, since there is a fully configurable blacklist, where you can regulate which words and ip to block and which not to block
