### ISSUE TITLE
[Feature Request] Ability to use <message> in staff alert message

### ISSUE THREAD

**Issue by D3adhkwen** [4drian3d/ChatRegulator#22]
**Is your feature request related to a problem? Please describe.**
The staff alert message now only shows the violation and server.

**Describe the solution you'd like**
Ability to display original message sent by infractor in staff alert message
For example:
`<red>The player <aqua><player></aqua> <red>was using many caps in the chat of <aqua><server></aqua> server. (<message>)`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by 4drian3d** [comment]
The placeholder will be `<string>` since the message in command alerts would be strange to be configured as `<message>`
