### ISSUE TITLE
[BUG] Chat signing issues

### ISSUE THREAD

**Issue by SenPr** [4drian3d/ChatRegulator#24]
**Describe the bug**
I'm getting the message "A plugin changed a signed chat message. The server may not accept it." on my proxy, while my server gets "SayWut sent message with invalid signature: <message>"

**To Reproduce**
Use infractions module to replace the messages.

**Expected behavior**
Replaced message get sent instead

**Comment by 4drian3d** [comment]
Minecraft 1.19 has changed the way messages are sent, I can't do anything about it. Any solution could be done from Velocity itself or by changing the `ControlType` mode to `BLOCK` instead of `REPLACE`

**Comment by 4drian3d** [comment]
The `problem` is solved in Velocity and will be applied with the update to 1.19.1, this is in case of clients with version 1.19 or lower, for version 1.19.1 there is no solution, you cannot change the messages in case you have a signed key https://github.com/PaperMC/Velocity/pull/772/commits/eb32a765206383a828445ba11789c9a88ca2b585
I will make a check in ChatRegulator to ignore the change of messages in this kind of cases

**Comment by 4drian3d** [comment]
For those who have this problem, you can use my plugin UnSignedVelocity https://modrinth.com/plugin/unsignedvelocity so that ChatRegulator can block chat messages and commands again
