### ISSUE TITLE
[BUG] Replace does not work on Carbon

### ISSUE THREAD

**Issue by SenPr** [4drian3d/ChatRegulator#27]
**Describe the bug**
I am currently using Carbon (https://github.com/Hexaoxide/Carbon) as my chat plugin. When I tested it without Carbon things do get replaced properly, with Carbon the original message is sent instead.

Weird thing is that EssentialsX Discord relay the replaced message, not the original.

**Comment by 4drian3d** [comment]
The bug seems to come from Carbon as it ignores the message modified by other plugins and only uses the original message https://github.com/Hexaoxide/Carbon/blob/2.1/velocity/src/main/java/net/draycia/carbon/velocity/listeners/VelocityChatListener.java#L82

**Comment by 4drian3d** [comment]
Fixed in https://github.com/Hexaoxide/Carbon/pull/209
