### ISSUE TITLE
Discord support, capslock update

### ISSUE THREAD

**Issue by Patryk-Suchecki** [4drian3d/ChatRegulator#28]
Hi, I would like to propose a new solution to the caps lock problem.
My suggestion is to change the maximum number of uppercase letters in the message to % uppercase in the message.
For long messages, this system would do much better.
For example, if the player's message is more than 60% uppercase. The player will get a warning

I would also like you to add support for the discord webhook.. This would make managing the server much easier when none of the administrators is online.
It would also provide interesting alert logs

**Comment by 4drian3d** [comment]
Next time, try to make separate issues for each feature/bug you report.

In the case of adding a number of capital letters instead of the percentage, I could do it soon.
As for the weebhook, it could be done in a separate plugin, that's why I implemented the events.
