### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by ArmaniS-Dev** [4drian3d/ChatRegulator#31]
This Error Code: Couldn't pass ProxyInitializeEvent to chatregulator
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)'

This error came on Start

Latest Velocity Version.
Java 16.

Please fix it.

**Comment by 4drian3d** [comment]
All my plugins require using the latest version of Velocity, install the latest version from https://papermc.io/downloads#Velocity.
