### ISSUE TITLE
[BUG] Blacklisted messages are not blocked.

### ISSUE THREAD

**Issue by Matt-MX** [4drian3d/ChatRegulator#32]
**Describe the bug**
When on the latest Velocity and ChatRegulator build, chat messages that include blacklitsed words or phrases are not blocked. You are given the warning message yet your messages are still sent.

**To Reproduce**
1. Install the ChatRegulator plugin latest version on the latest velocity release.
2. Log on, test a message, you should see that your message goes through no matter what.

**Expected behavior**
Usually your messages would be blocked as prior behaviour of the plugin. However this bug allows players to say whatever vulgarities they want.

**Additional context**
Tested on both my production server and a brand new fresh local velocity server, behaviour persists.

**Comment by 4drian3d** [comment]
Are you using a 1.19.1 or higher client with a Minecraft Premium account?

**Comment by Matt-MX** [comment]
Yes, backend is 1.19.2, and the client is 1.19.2
Other plugins installed:
- LuckPerms Velocity
- ViaVersion (About to test without)

**Comment by 4drian3d** [comment]
> Yes, backend is 1.19.2, and the client is 1.19.2 Other plugins installed:
> 
>     * LuckPerms Velocity
> 
>     * ViaVersion (About to test without)

In that case, there is nothing I can do. The only options are to block the message and have the user kicked or simply not block the message (which is done now). This is caused by the 1.19.1 update.
https://github.com/4drian3d/ChatRegulator/issues/24
