### ISSUE TITLE
[Feature Request] Add Option to Log Filter Catches to a Different Log File

### ISSUE THREAD

**Issue by Aiidoneus** [4drian3d/ChatRegulator#63]
By default, if chat regulator catches someone breaking the blacklist filter or any filter, it logs it to velocity's log file. I was wondering if we can have the filter log moved to a log file system within the ``/plugins/chatregulator`` folder? Hopefully this makes sense.

**Comment by 4drian3d** [comment]
I liked the idea, I have to think well how to implement it in the best way, but I will try to have it available for the BETA 3 of the 4.0.0 version
